In [1]:
#Tudo em Ciências de Dados e IA são matrizes.

In [1]:
#importando a biblioteca Numpy com um nome np para facilitar o código
import numpy as np

# Criando Arrays apartir de Lista

In [12]:
arr1 = np.array([10, 20, 42, 56, 88, 15])

In [13]:
print(arr1)

[10 20 42 56 88 15]


Um array pode ter n dimensões

1 dimensão = vetor

2 dimensões = matrizes

3 dimensões = largura + profundidade + largura

...

# Indexação

In [14]:
#imprimindo valor do índice 4:
print(arr1[4])

88


In [15]:
#iniciando do 1 e excluindo o 4
print(arr1[1:4])

[20 42 56]


In [16]:
indices = [0, 2, 4]

In [17]:
print(arr1[indices])

[10 42 88]


In [18]:
#Máscara booleana que só retorna os pares
mask = (arr1 % 2 == 0)

In [19]:
print(arr1[mask])

[10 20 42 56 88]


In [20]:
mask

array([ True,  True,  True,  True,  True, False])

In [21]:
#Substituindo valores
arr1[5] = 16
print(arr1)

[10 20 42 56 88 16]


# Funções

In [22]:
arr2 = np.array([1, 2, 3, 4, 5])

In [23]:
#verificando tipo do objeto
type(arr2)

numpy.ndarray

digite o nome do objeto + "." e aperte a tecla tab para vizualizar os métodos disponíveis

In [24]:
#A função arange cria um array NumPy contendo uma progressão aritmética a partir de um intervalo - start, stop, step

In [26]:
arr3 = np.arange(0, 50, 5)

In [27]:
#veja que 50 não entra pois o último 
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [2]:
#criando um array preenchido por zeros em x posicoes
arr4 = np.zeros(4)

In [3]:
print(arr4)

[0. 0. 0. 0.]


In [7]:
#retornando 1 na diagonal e 0 no resto da matriz
arr5 = np.eye(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#passando valores para preencher diagonalmente
arr6 = np.diag(np.array([1, 2, 3, 4]))
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [12]:
#Array de valores booleanos
arr7 = [True, False, True, True]

O método linspace (linearly spaced vector) retorna um número de valores igualmente 
distribuídos no intervalo especificado.

In [13]:
print(np.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [14]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


A função logspace do NumPy é usada para criar uma sequência de números igualmente espaçados em escala logarítmica dentro de um intervalo especificado. Essa função é amplamente utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos,
cálculos e simulações.

In [ ]:
p