In [2]:
import numpy as np
#Criando matriz apartir de uma lista de listas
arr = np.array([ [1, 2, 3], [4, 5, 6]  ])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
#verificando linhas e colunas
print(arr.shape)

(2, 3)


In [4]:
#criando uma matriz com 1's
arr1 = np.ones((2, 3))

In [5]:
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#outra forma de fazer
lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr2 = np.array(lista)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#verifica tamanho da matriz
arr2.size

9

# Indexação

In [17]:
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(arr3[1,2])

6


In [20]:
#linha apartir da 1 até a 3 sem contar 3, e coluna 1
print(arr3[1:3,1])

[5 8]


In [21]:
#alterando elemento da matriz
arr3[1,1] = 1
print(arr3)

[[1 2 3]
 [4 1 6]
 [7 8 9]]


In [30]:
arr4 = np.array([[1,2,3], [3,2,1]], dtype = float)
print(arr4)

[[1. 2. 3.]
 [3. 2. 1.]]


In [32]:
#definir o tipo é importante para resolver operações matemáticas, evitando o arredondamento

O itemsize de um array numpy é um atributo que retorna o tamanho em bytes de cada elemento do array. Em outras palavras, o itemsize representa o número de bytes necessários para armazenar cada valor do array numpy.

In [33]:
#tamanho de cada elemento
arr4.itemsize

8

In [34]:
#tamanho total dos elementos
arr4.nbytes

48

In [35]:
#numero de dimensões
arr4.ndim

2