In [1]:
import numpy as np

In [5]:
arr = np.arange(1,10)

In [6]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
#Soma
np.sum(arr)
print(np.sum(arr))

45


In [9]:
#Multiplicao
np.prod(arr)
print(np.prod(arr))

362880


In [10]:
#Acumula a soma dos elementos
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [11]:
arr2 = np.array([1, 2, 3])
arr3 = np.array([40 , 10, 30])

In [16]:
#Somando Arrays
arr4 = np.add(arr2,arr3)
print(arr4)

[41 12 33]


Para multiplicar duas matrizes NumPy, podemos usar a função dot ou o operador @. Ambos os métodos executam a multiplicação matricial. É importante lembrar que, para que a multiplicação de matrizes possa ser executada, o número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.
Há várias formas de multiplicar elementos de matrizes NumPy. A função dot é um método bastante utilizado.

In [20]:
matriz1 = np.array([[1, 2],[1, 2]])
matriz2 = np.array([[3, 4], [5, 6]])
print(matriz1)
print(matriz2)

[[1 2]
 [1 2]]
[[3 4]
 [5 6]]


In [22]:
#OBS: ambas devem ter o mesmo numero de linhas e colunas (mesmo .shape)

In [24]:
matriz3 = np.dot(matriz1 , matriz2)
print(matriz3)

[[13 16]
 [13 16]]
