In [1]:
#Comparando
import numpy

a = numpy.array([1, 2, 3 , 4])
b = numpy.array([1, 2, 3 , 5])

In [2]:
a == b

array([ True,  True,  True, False])

In [3]:
#Comparação Globsl
numpy.array_equal(a, b)

False

In [8]:
#Somando um valor a cada elemento do array 
a + 1.5

array([2.5, 3.5, 4.5, 5.5])

In [10]:
#Arredonda
c = numpy.around(a)
print(c)

[1 2 3 4]


Flatten: O método flatten com NumPy é usado para criar uma cópia unidimensional (ou "achatada") de um array multidimensional.

In [12]:
arr = numpy.array([[1, 2, 2], [5,  6, 8]])
print(arr)

[[1 2 2]
 [5 6 8]]


In [13]:
arr1 = arr.flatten()
print(arr1)

[1 2 2 5 6 8]


In [15]:
#Repetindo valores de um array
arr2 = numpy.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [18]:
arr3 = numpy.repeat(arr2, 4)
print(arr3)

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6]


In [ ]:
#Copiando um array
arr3