In [3]:
#Manipulando objetos de 3 e 4 dimensões
import numpy
#criando um array com 3 dimensões:
arr = numpy.array([
        [
            [1, 2, 3],
            [4, 5 , 6],
            [7, 8, 9]
        ], [
            [10, 11, 12],
            [13, 14, 15], 
            [16, 17, 18]
        ]
    ])

In [4]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [5]:
arr.size

18

In [7]:
#qntd de elementos, linhas e colunas
arr.shape

(2, 3, 3)

In [12]:
print(arr[0,2,2])

9
