In [6]:
import numpy as np
#Criando matriz apartir de uma lista de listas
arr = np.array([ [1, 2, 3], [4, 5, 6]  ])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
#verificando linhas e colunas
print(arr.shape)

(2, 3)


In [12]:
#criando uma matriz com 1's
arr1 = np.ones((2, 3))

In [13]:
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#outra forma de fazer
lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
arr2 = np.array(lista)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#verifica tamanho da matriz
arr2.size

9